# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv: ['.env']

tasks:
  up:
    desc: |
      Bootstrap fresh lab environment
    deps:
      - kind-create
    cmds:
      - task: install-argo
      - task: install-gateway-api
      - task: install-agentgateway


  down:
    desc: |
      Tear-down the lab environment
    deps:
      - kind-destroy

  kind-create:
    desc: |
      Create a kind cluster with context aire-lab
    cmd: kind create cluster --name aire-lab --config infra/kind/config.yaml
    status:
      - kind get clusters | grep -qx aire-lab

  kind-destroy:
    desc: |
      Prune the lab kind cluster - needed for fresh installation
    cmd: kind delete cluster --name aire-lab


  install-argo:
    desc: |
      Install argo cd chart onto the cluster; has to be done as part of bootstrap
    cmds:
      - kubectl create namespace argocd --context kind-aire-lab
      - kubectl apply -n argocd --server-side --force-conflicts -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml --context kind-aire-lab
    status:
      - kubectl get namespace argocd

  install-gateway-api:
    desc: |
      Install k8s Gateway API through the Standard Channel
    cmds: 
      - kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.0/standard-install.yaml --context kind-aire-lab

  install-agentgateway:
    desc: |
      Install agent gateway argo application
    cmds: 
      - kubectl apply -f infra/agentgateway/app-crds.yaml
      - kubectl apply -f infra/agentgateway/app-chart.yaml

  apply-secrets:
    desc: |
      Apply secrets necessary for proper application functioning
    cmds:
      - |
        kubectl apply -f- <<EOF
        apiVersion: v1
        kind: Secret
        metadata:
          name: gemini-secret
          namespace: agentgateway-system
        type: Opaque
        stringData:
          Authorization: $GEMINI_API_KEY
        EOF


  deploy:
    desc: |
      Deploy workloads onto the cluster - presumes that all dependencies have been isntalled already
    deps:
      - apply-secrets
    cmds:
      - helm upgrade --install aire-lab ./chart
