apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: aire-model-config
  namespace: kagent
spec:
  model: {{ .Values.agentgateway.backends.gemini.model }}
  provider: OpenAI
  apiKeySecret: dummy-api-key
  apiKeySecretKey: api-key
  openAI:
    baseUrl: http://{{ .Values.agentgateway.proxy.name }}.{{ .Values.agentgateway.namespace }}.svc.cluster.local{{ .Values.agentgateway.backends.gemini.route.path }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dummy-api-key
  namespace: kagent
type: Opaque
stringData:
  api-key: "sk-agentgateway-placeholder"
---