apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: kagent
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    helm:
      valuesObject:
        # Default provider configuration
        providers:
          openAI:
            model: gemini-3-flash-preview
            apiKeySecretRef: gemini-secret
            apiKeySecretKey: apiKey
            baseURL: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:80"

        kmcp:
          enabled: true
        tools:
          grafana-mcp:
            enabled: false
          querydoc:
            enabled: false
        agents:
          k8s-agent:
            enabled: false
          kgateway-agent:
            enabled: false
          istio-agent:
            enabled: false
          promql-agent:
            enabled: false
          observability-agent:
            enabled: false
          argo-rollouts-agent:
            enabled: false
          helm-agent:
            enabled: false
          cilium-policy-agent:
            enabled: false
          cilium-manager-agent:
            enabled: false
          cilium-debug-agent:
            enabled: false
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm/kagent
    targetRevision: "0.7.23"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true