apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: kagent
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kagent-crds
    helm:
      skipCrds: false
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm
    targetRevision: "0.7"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true