apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aire-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: https://github.com/ikaliuzh/aire-agents.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true